default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  host: localhost
  #username: username
  #password: password

development:
  <<: *default
  database: staple_themes_development

test:
  <<: *default
  database: staple_themes_test

production:
  <<: *default
  database: staple_themes_production
  username: staple
  password: staple
  host: localhost
  port: 5432