version: "2"
services:
  my-wpdb:
    image: mariadb:latest
    container_name: wordpress_db
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
    volumes:
      - my-wpdata:/var/lib/mysql
  my-wp:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress/:/var/www/html
    ports:
      - "80:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - my-wpdb:mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
      PMA_HOST: mysql
    restart: always
    ports:
     - 8181:80

volumes:
  my-wpdata: